# Generated by Django 6.1 on 2026-09-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=2, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
