# Generated by Django 6.1 on 2026-09-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
